name = "GlobalSearchRegression"
uuid = "5b3bc22e-96cb-5e8b-bdf1-153217652f04"
authors = ["Demian Panigo <panigo@gmail.com>", "Adán Mauri Ungaro <adan.mauri@gmail.com>", "Nicolás Monzón <nicomzn4@gmail.com>", "Valentin Mari <valentinmari@hotmail.com>"]
version = "2.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMNet = "8d5ece8b-de18-5317-b113-243142960cc6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SingularSpectrumAnalysis = "77f5812f-bd1f-5f6e-9b72-07b28d8bbbc3"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ShiftedArrays = "1277b4bf-5013-50f5-be3d-901d8477a67a"
